"""
Offline communication-log summarizer for ARCE / OpenCOOD experiments.

This script reads ARCE communication logs generated by:

    opencood/tools/inference_arce.py
    opencood.communication.metrics.comm_logger.CommLogger

and produces offline summaries.

Supported input files:
    1. Raw nested records:
        arce_comm_records.jsonl

    2. Flat metric records:
        arce_comm_flat.jsonl

Preferred input:
    arce_comm_records.jsonl

If raw records are available, this script extracts flat metrics again and
summarizes them. If only flat records are available, it summarizes those
directly.

Typical usage:

    python opencood/tools/summarize_comm_logs.py \\
      --log_dir opencood/logs/xxx/arce_comm_logs

or:

    python opencood/tools/summarize_comm_logs.py \\
      --model_dir opencood/logs/xxx

Outputs:
    <prefix>_summary_from_logs.json
        Compact + overall summary.

    <prefix>_summary_full_from_logs.json
        Overall + by-frame + by-channel + by-quant + by-FEC summary.

    <prefix>_flat_from_logs.csv
        Flat per-link metric table.

    <prefix>_group_summary_from_logs.csv
        One CSV containing overall / by-frame / by-channel / by-quant / by-FEC
        summaries.

    <prefix>_report_from_logs.md
        Human-readable markdown report.

This script does NOT:
    - rerun inference;
    - modify model outputs;
    - compute detection AP;
    - simulate communication.

It only summarizes already saved ARCE communication logs.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import os
import sys
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple


# ----------------------------------------------------------------------
# Make project root importable when running:
#   python opencood/tools/summarize_comm_logs.py
# ----------------------------------------------------------------------

PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))


from opencood.communication.metrics import (  # noqa: E402
    METRIC_CHANNEL_STATE,
    METRIC_QUANT_MODE,
    METRIC_FEC_TYPE,
    METRIC_TRANSMITTED_BYTES,
    METRIC_RECEIVED_BYTES,
    METRIC_NUM_ENCODED_PACKETS,
    METRIC_NUM_LOST_PACKETS,
    METRIC_NUM_FEC_RECOVERED,
    METRIC_NUM_TEMPORAL_FILLED,
    METRIC_NUM_SPATIAL_FILLED,
    METRIC_NUM_ZERO_FILLED,
    METRIC_NUM_STILL_MISSING,
    METRIC_PACKET_LOSS_RATIO,
    METRIC_RECOVERY_RATIO,
    extract_record_metrics,
    flatten_dict,
    bytes_to_mb,
    to_float,
    to_int,
)

from opencood.communication.metrics.comm_stats import CommStats  # noqa: E402


DEFAULT_PREFIX = "arce_comm"

RAW_JSONL_SUFFIX = "_records.jsonl"
FLAT_JSONL_SUFFIX = "_flat.jsonl"

SUMMARY_OUT_SUFFIX = "_summary_from_logs.json"
FULL_SUMMARY_OUT_SUFFIX = "_summary_full_from_logs.json"
FLAT_CSV_OUT_SUFFIX = "_flat_from_logs.csv"
GROUP_SUMMARY_CSV_SUFFIX = "_group_summary_from_logs.csv"
REPORT_OUT_SUFFIX = "_report_from_logs.md"


# ----------------------------------------------------------------------
# Argument parser
# ----------------------------------------------------------------------

def build_parser() -> argparse.ArgumentParser:
    """
    Build command-line parser.
    """
    parser = argparse.ArgumentParser(
        description="Summarize ARCE communication logs."
    )

    group = parser.add_mutually_exclusive_group(required=True)

    group.add_argument(
        "--log_dir",
        type=str,
        default=None,
        help=(
            "Directory containing ARCE communication logs, e.g. "
            "opencood/logs/xxx/arce_comm_logs."
        ),
    )

    group.add_argument(
        "--model_dir",
        type=str,
        default=None,
        help=(
            "OpenCOOD model directory. The script will use "
            "<model_dir>/arce_comm_logs as log_dir."
        ),
    )

    parser.add_argument(
        "--prefix",
        type=str,
        default=DEFAULT_PREFIX,
        help="Communication log prefix. Default: arce_comm.",
    )

    parser.add_argument(
        "--input_jsonl",
        type=str,
        default=None,
        help=(
            "Optional explicit input jsonl path. If omitted, the script tries "
            "<prefix>_records.jsonl first, then <prefix>_flat.jsonl."
        ),
    )

    parser.add_argument(
        "--input_type",
        type=str,
        default="auto",
        choices=["auto", "raw", "flat"],
        help=(
            "Input jsonl type. raw means nested ARCE records. "
            "flat means extracted flat metric records."
        ),
    )

    parser.add_argument(
        "--prefer_flat",
        action="store_true",
        help=(
            "Prefer <prefix>_flat.jsonl over <prefix>_records.jsonl when both exist."
        ),
    )

    parser.add_argument(
        "--output_dir",
        type=str,
        default=None,
        help=(
            "Output directory for summaries. Default: same as log_dir."
        ),
    )

    parser.add_argument(
        "--skip_bypassed",
        action="store_true",
        help="Skip bypassed records, such as ego/local features, in summaries.",
    )

    parser.add_argument(
        "--write_flat_csv",
        action="store_true",
        help="Write flat per-link CSV.",
    )

    parser.add_argument(
        "--write_group_csv",
        action="store_true",
        help="Write grouped summary CSV.",
    )

    parser.add_argument(
        "--write_report",
        action="store_true",
        help="Write markdown report.",
    )

    parser.add_argument(
        "--all_outputs",
        action="store_true",
        help="Write JSON summaries, flat CSV, group CSV, and markdown report.",
    )

    parser.add_argument(
        "--extra_group_by",
        type=str,
        nargs="*",
        default=[],
        help=(
            "Additional flat metric keys to group by. Example: "
            "--extra_group_by channel_state quant_mode fec_type"
        ),
    )

    parser.add_argument(
        "--print_records",
        type=int,
        default=0,
        help="Print first N flat metric records for quick inspection.",
    )

    parser.add_argument(
        "--quiet",
        action="store_true",
        help="Do not print compact summary.",
    )

    return parser


# ----------------------------------------------------------------------
# Basic IO helpers
# ----------------------------------------------------------------------

def ensure_dir(path: Path) -> Path:
    """
    Create directory if missing.
    """
    path.mkdir(parents=True, exist_ok=True)
    return path


def json_safe(value: Any) -> Any:
    """
    Convert values to JSON-friendly types.
    """
    if value is None:
        return None

    if isinstance(value, (str, int, bool)):
        return value

    if isinstance(value, float):
        return value if math.isfinite(value) else None

    if isinstance(value, dict):
        return {str(k): json_safe(v) for k, v in value.items()}

    if isinstance(value, (list, tuple)):
        return [json_safe(v) for v in value]

    return str(value)


def load_jsonl(path: Path) -> List[Dict[str, Any]]:
    """
    Load JSONL file.

    Parameters
    ----------
    path : Path
        JSONL file path.

    Returns
    -------
    list of dict
        Loaded records.
    """
    if not path.exists():
        raise FileNotFoundError(f"JSONL file does not exist: {path}")

    records: List[Dict[str, Any]] = []

    with path.open("r", encoding="utf-8") as f:
        for line_idx, line in enumerate(f, start=1):
            line = line.strip()

            if not line:
                continue

            try:
                item = json.loads(line)
            except json.JSONDecodeError as exc:
                raise json.JSONDecodeError(
                    f"Failed to parse {path} at line {line_idx}: {exc.msg}",
                    exc.doc,
                    exc.pos,
                )

            if not isinstance(item, dict):
                raise ValueError(
                    f"Each JSONL line should be a dict. "
                    f"Got {type(item)} at line {line_idx} in {path}."
                )

            records.append(item)

    return records


def write_json(path: Path, data: Any, indent: int = 2) -> None:
    """
    Write JSON file.
    """
    with path.open("w", encoding="utf-8") as f:
        json.dump(json_safe(data), f, indent=indent, ensure_ascii=False)


def collect_csv_fieldnames(records: Sequence[Dict[str, Any]]) -> List[str]:
    """
    Collect stable CSV fieldnames from records.
    """
    fieldnames: List[str] = []
    seen = set()

    for record in records:
        for key in record.keys():
            if key not in seen:
                seen.add(key)
                fieldnames.append(key)

    return fieldnames


def csv_value(value: Any) -> Any:
    """
    Convert value for CSV writing.
    """
    value = json_safe(value)

    if isinstance(value, (dict, list, tuple)):
        return json.dumps(value, ensure_ascii=False)

    return value


def write_csv(path: Path, records: Sequence[Dict[str, Any]]) -> None:
    """
    Write records to CSV.
    """
    records = [json_safe(r) for r in records]

    fieldnames = collect_csv_fieldnames(records)

    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=fieldnames,
            extrasaction="ignore",
        )
        writer.writeheader()

        for record in records:
            row = {key: csv_value(record.get(key, "")) for key in fieldnames}
            writer.writerow(row)


# ----------------------------------------------------------------------
# Input resolving / type inference
# ----------------------------------------------------------------------

def resolve_log_dir(opt: argparse.Namespace) -> Path:
    """
    Resolve log directory from --log_dir or --model_dir.
    """
    if opt.log_dir is not None:
        return Path(opt.log_dir).resolve()

    if opt.model_dir is not None:
        return (Path(opt.model_dir).resolve() / "arce_comm_logs")

    raise ValueError("Either --log_dir or --model_dir should be provided.")


def resolve_output_dir(opt: argparse.Namespace, log_dir: Path) -> Path:
    """
    Resolve output directory.
    """
    if opt.output_dir is not None:
        return ensure_dir(Path(opt.output_dir).resolve())

    return ensure_dir(log_dir)


def resolve_input_path(opt: argparse.Namespace, log_dir: Path) -> Tuple[Path, str]:
    """
    Resolve input JSONL path and guessed type.

    Returns
    -------
    tuple
        (path, guessed_type)
    """
    prefix = opt.prefix

    if opt.input_jsonl is not None:
        path = Path(opt.input_jsonl).resolve()
        guessed = "auto" if opt.input_type == "auto" else opt.input_type
        return path, guessed

    raw_path = log_dir / f"{prefix}{RAW_JSONL_SUFFIX}"
    flat_path = log_dir / f"{prefix}{FLAT_JSONL_SUFFIX}"

    if opt.prefer_flat:
        if flat_path.exists():
            return flat_path, "flat"
        if raw_path.exists():
            return raw_path, "raw"
    else:
        if raw_path.exists():
            return raw_path, "raw"
        if flat_path.exists():
            return flat_path, "flat"

    raise FileNotFoundError(
        "Could not find ARCE communication jsonl input. Tried:\n"
        f"  raw:  {raw_path}\n"
        f"  flat: {flat_path}\n"
        "You can also pass --input_jsonl explicitly."
    )


def infer_record_type(records: Sequence[Dict[str, Any]], fallback: str = "auto") -> str:
    """
    Infer whether records are raw nested records or flat metric records.

    Returns
    -------
    str
        raw or flat
    """
    if fallback in ("raw", "flat"):
        return fallback

    if not records:
        return "flat"

    sample = records[0]

    raw_keys = (
        "size",
        "channel",
        "action",
        "packetization",
        "quantization",
        "fec_decode",
        "partial_reconstruction",
    )

    if any(key in sample for key in raw_keys):
        return "raw"

    flat_keys = (
        METRIC_TRANSMITTED_BYTES,
        METRIC_PACKET_LOSS_RATIO,
        METRIC_CHANNEL_STATE,
        METRIC_QUANT_MODE,
        METRIC_FEC_TYPE,
    )

    if any(key in sample for key in flat_keys):
        return "flat"

    # Conservative fallback:
    # raw records usually have nested dictionaries; flat metrics usually do not.
    if any(isinstance(v, dict) for v in sample.values()):
        return "raw"

    return "flat"


# ----------------------------------------------------------------------
# Stats building
# ----------------------------------------------------------------------

def build_stats(
    records: Sequence[Dict[str, Any]],
    record_type: str,
    skip_bypassed: bool = False,
) -> CommStats:
    """
    Build CommStats from raw or flat records.
    """
    stats = CommStats(
        records=None,
        skip_bypassed=skip_bypassed,
        keep_records=True,
        keep_flat_metrics=True,
    )

    if record_type == "raw":
        stats.update(records)
        return stats

    if record_type == "flat":
        for item in records:
            stats.add_metrics(item)
        return stats

    raise ValueError(f"Unsupported record_type: {record_type}")


def get_flat_records(
    records: Sequence[Dict[str, Any]],
    record_type: str,
    skip_bypassed: bool = False,
) -> List[Dict[str, Any]]:
    """
    Return flat metric records.
    """
    flat_records: List[Dict[str, Any]] = []

    if record_type == "raw":
        for record in records:
            metrics = extract_record_metrics(record)

            if skip_bypassed and bool(metrics.get("bypassed", False)):
                continue

            flat_records.append(json_safe(metrics))

        return flat_records

    if record_type == "flat":
        for metrics in records:
            if skip_bypassed and bool(metrics.get("bypassed", False)):
                continue

            flat_records.append(json_safe(metrics))

        return flat_records

    raise ValueError(f"Unsupported record_type: {record_type}")


# ----------------------------------------------------------------------
# Summary formatting
# ----------------------------------------------------------------------

def flatten_summary_row(
    group_type: str,
    group_key: str,
    summary: Dict[str, Any],
) -> Dict[str, Any]:
    """
    Flatten one summary into one CSV row.
    """
    row = {
        "group_type": group_type,
        "group_key": group_key,
    }

    flat = flatten_dict(summary, sep=".", max_depth=None)

    for key, value in flat.items():
        row[key] = value

    return row


def build_group_summary_rows(full_summary: Dict[str, Any]) -> List[Dict[str, Any]]:
    """
    Build one table containing overall and grouped summaries.
    """
    rows: List[Dict[str, Any]] = []

    overall = full_summary.get("overall", {}) or {}
    rows.append(flatten_summary_row("overall", "all", overall))

    group_map = {
        "frame": full_summary.get("by_frame", {}) or {},
        "channel_state": full_summary.get("by_channel_state", {}) or {},
        "quant_mode": full_summary.get("by_quant_mode", {}) or {},
        "fec_type": full_summary.get("by_fec_type", {}) or {},
    }

    for group_type, group_dict in group_map.items():
        for group_key, summary in group_dict.items():
            rows.append(
                flatten_summary_row(
                    group_type=group_type,
                    group_key=str(group_key),
                    summary=summary,
                )
            )

    return rows


def format_float(value: Any, digits: int = 6) -> str:
    """
    Format float-like value for markdown.
    """
    try:
        value = float(value)
    except (TypeError, ValueError):
        return str(value)

    if abs(value) >= 1000:
        return f"{value:.2f}"

    return f"{value:.{digits}f}"


def markdown_table(rows: Sequence[Tuple[str, Any]]) -> str:
    """
    Build a simple two-column markdown table.
    """
    lines = [
        "| Metric | Value |",
        "| --- | ---: |",
    ]

    for key, value in rows:
        if isinstance(value, float):
            value = format_float(value)
        lines.append(f"| {key} | {value} |")

    return "\n".join(lines)


def extract_compact_for_report(summary: Dict[str, Any]) -> List[Tuple[str, Any]]:
    """
    Extract compact report rows.
    """
    compact = summary.get("compact", {}) or {}

    return [
        ("num_records", compact.get("num_records", 0)),
        ("num_non_bypassed_records", compact.get("num_non_bypassed_records", 0)),
        ("total_transmitted_mb", compact.get("total_transmitted_mb", 0.0)),
        ("total_received_mb", compact.get("total_received_mb", 0.0)),
        ("total_source_packets", compact.get("total_source_packets", 0)),
        ("total_encoded_packets", compact.get("total_encoded_packets", 0)),
        ("total_lost_packets", compact.get("total_lost_packets", 0)),
        ("overall_packet_loss_ratio", compact.get("overall_packet_loss_ratio", 0.0)),
        ("total_fec_recovered_packets", compact.get("total_fec_recovered_packets", 0)),
        ("total_temporal_filled_packets", compact.get("total_temporal_filled_packets", 0)),
        ("total_spatial_filled_packets", compact.get("total_spatial_filled_packets", 0)),
        ("total_zero_filled_packets", compact.get("total_zero_filled_packets", 0)),
        ("total_still_missing_packets", compact.get("total_still_missing_packets", 0)),
        ("mean_packet_loss_ratio", compact.get("mean_packet_loss_ratio", 0.0)),
        ("mean_recovery_ratio", compact.get("mean_recovery_ratio", 0.0)),
    ]


def build_group_brief_rows(group_summary: Dict[str, Any]) -> List[Tuple[str, Any]]:
    """
    Build compact rows for one group summary.
    """
    sums = group_summary.get("sum", {}) or {}
    means = group_summary.get("mean", {}) or {}

    return [
        ("num_records", group_summary.get("num_records", 0)),
        ("num_non_bypassed_records", group_summary.get("num_non_bypassed_records", 0)),
        ("total_transmitted_mb", group_summary.get("total_transmitted_mb", 0.0)),
        ("total_received_mb", group_summary.get("total_received_mb", 0.0)),
        ("overall_packet_loss_ratio", group_summary.get("overall_packet_loss_ratio", 0.0)),
        ("sum_fec_recovered", sums.get(METRIC_NUM_FEC_RECOVERED, 0)),
        ("sum_temporal_filled", sums.get(METRIC_NUM_TEMPORAL_FILLED, 0)),
        ("sum_spatial_filled", sums.get(METRIC_NUM_SPATIAL_FILLED, 0)),
        ("sum_zero_filled", sums.get(METRIC_NUM_ZERO_FILLED, 0)),
        ("mean_recovery_ratio", means.get(f"mean_{METRIC_RECOVERY_RATIO}", 0.0)),
    ]


def build_markdown_report(
    input_path: Path,
    record_type: str,
    num_input_records: int,
    summary_payload: Dict[str, Any],
    full_summary: Dict[str, Any],
) -> str:
    """
    Build human-readable markdown report.
    """
    lines: List[str] = []

    lines.append("# ARCE Communication Log Summary")
    lines.append("")
    lines.append(f"- Input: `{input_path}`")
    lines.append(f"- Input type: `{record_type}`")
    lines.append(f"- Input records: `{num_input_records}`")
    lines.append("")

    lines.append("## Overall compact summary")
    lines.append("")
    lines.append(markdown_table(extract_compact_for_report(summary_payload)))
    lines.append("")

    by_channel = full_summary.get("by_channel_state", {}) or {}
    if by_channel:
        lines.append("## By channel state")
        lines.append("")
        for key, item in by_channel.items():
            lines.append(f"### `{key}`")
            lines.append("")
            lines.append(markdown_table(build_group_brief_rows(item)))
            lines.append("")

    by_quant = full_summary.get("by_quant_mode", {}) or {}
    if by_quant:
        lines.append("## By quantization mode")
        lines.append("")
        for key, item in by_quant.items():
            lines.append(f"### `{key}`")
            lines.append("")
            lines.append(markdown_table(build_group_brief_rows(item)))
            lines.append("")

    by_fec = full_summary.get("by_fec_type", {}) or {}
    if by_fec:
        lines.append("## By FEC type")
        lines.append("")
        for key, item in by_fec.items():
            lines.append(f"### `{key}`")
            lines.append("")
            lines.append(markdown_table(build_group_brief_rows(item)))
            lines.append("")

    lines.append("## Notes")
    lines.append("")
    lines.append(
        "- `source_packets` are original spatial feature packets."
    )
    lines.append(
        "- `encoded_packets` include source packets plus FEC parity / repair packets."
    )
    lines.append(
        "- GE packet loss acts on encoded packets, not only source packets."
    )
    lines.append(
        "- FEC / temporal / spatial / zero-fill counts describe how missing source packets were handled after channel loss."
    )
    lines.append("")

    return "\n".join(lines)


def print_compact_summary(compact: Dict[str, Any]) -> None:
    """
    Print compact summary.
    """
    msg = (
        "[ARCE summarize_comm_logs] "
        f"records={compact.get('num_records', 0)} "
        f"non_bypassed={compact.get('num_non_bypassed_records', 0)} "
        f"tx={compact.get('total_transmitted_mb', 0.0):.4f}MB "
        f"rx={compact.get('total_received_mb', 0.0):.4f}MB "
        f"loss={compact.get('overall_packet_loss_ratio', 0.0):.4f} "
        f"fec_rec={compact.get('total_fec_recovered_packets', 0)} "
        f"tmp={compact.get('total_temporal_filled_packets', 0)} "
        f"spatial={compact.get('total_spatial_filled_packets', 0)} "
        f"zero={compact.get('total_zero_filled_packets', 0)}"
    )
    print(msg)


# ----------------------------------------------------------------------
# Extra grouping
# ----------------------------------------------------------------------

def write_extra_group_summaries(
    stats: CommStats,
    output_dir: Path,
    prefix: str,
    group_keys: Sequence[str],
) -> Dict[str, str]:
    """
    Write additional grouped summary JSON files.
    """
    written: Dict[str, str] = {}

    for key in group_keys:
        key = str(key).strip()
        if not key:
            continue

        summary = stats.summarize_by_metric_key(key)

        safe_key = key.replace("/", "_").replace(".", "_")
        out_path = output_dir / f"{prefix}_by_{safe_key}_from_logs.json"

        write_json(out_path, summary)
        written[key] = str(out_path)

    return written


# ----------------------------------------------------------------------
# Main
# ----------------------------------------------------------------------

def main(opt: argparse.Namespace) -> None:
    """
    Main entry.
    """
    log_dir = resolve_log_dir(opt)
    output_dir = resolve_output_dir(opt, log_dir)

    input_path, guessed_type = resolve_input_path(opt, log_dir)

    records = load_jsonl(input_path)

    record_type = infer_record_type(
        records,
        fallback=opt.input_type if opt.input_type != "auto" else guessed_type,
    )

    stats = build_stats(
        records=records,
        record_type=record_type,
        skip_bypassed=opt.skip_bypassed,
    )

    compact = stats.get_compact_summary()
    overall = stats.summarize()
    full_summary = stats.full_summary().as_dict()

    summary_payload = {
        "compact": compact,
        "overall": overall,
        "input": {
            "path": str(input_path),
            "type": record_type,
            "num_records": int(len(records)),
            "log_dir": str(log_dir),
            "skip_bypassed": bool(opt.skip_bypassed),
        },
    }

    prefix = opt.prefix

    summary_path = output_dir / f"{prefix}{SUMMARY_OUT_SUFFIX}"
    full_summary_path = output_dir / f"{prefix}{FULL_SUMMARY_OUT_SUFFIX}"
    flat_csv_path = output_dir / f"{prefix}{FLAT_CSV_OUT_SUFFIX}"
    group_csv_path = output_dir / f"{prefix}{GROUP_SUMMARY_CSV_SUFFIX}"
    report_path = output_dir / f"{prefix}{REPORT_OUT_SUFFIX}"

    write_json(summary_path, summary_payload)
    write_json(full_summary_path, full_summary)

    should_write_flat_csv = bool(opt.write_flat_csv or opt.all_outputs)
    should_write_group_csv = bool(opt.write_group_csv or opt.all_outputs)
    should_write_report = bool(opt.write_report or opt.all_outputs)

    if should_write_flat_csv:
        flat_records = get_flat_records(
            records=records,
            record_type=record_type,
            skip_bypassed=opt.skip_bypassed,
        )
        write_csv(flat_csv_path, flat_records)

    if should_write_group_csv:
        group_rows = build_group_summary_rows(full_summary)
        write_csv(group_csv_path, group_rows)

    if should_write_report:
        report = build_markdown_report(
            input_path=input_path,
            record_type=record_type,
            num_input_records=len(records),
            summary_payload=summary_payload,
            full_summary=full_summary,
        )
        report_path.write_text(report, encoding="utf-8")

    extra_written = {}
    if opt.extra_group_by:
        extra_written = write_extra_group_summaries(
            stats=stats,
            output_dir=output_dir,
            prefix=prefix,
            group_keys=opt.extra_group_by,
        )

    if opt.print_records > 0:
        flat_records = get_flat_records(
            records=records,
            record_type=record_type,
            skip_bypassed=opt.skip_bypassed,
        )
        print(f"[ARCE summarize_comm_logs] First {opt.print_records} flat records:")
        for idx, item in enumerate(flat_records[: opt.print_records]):
            print(f"--- record {idx} ---")
            print(json.dumps(json_safe(item), indent=2, ensure_ascii=False))

    if not opt.quiet:
        print_compact_summary(compact)
        print("[ARCE summarize_comm_logs] Outputs:")
        print(f"  - summary_json:      {summary_path}")
        print(f"  - full_summary_json: {full_summary_path}")

        if should_write_flat_csv:
            print(f"  - flat_csv:          {flat_csv_path}")

        if should_write_group_csv:
            print(f"  - group_csv:         {group_csv_path}")

        if should_write_report:
            print(f"  - report_md:         {report_path}")

        for key, path in extra_written.items():
            print(f"  - by_{key}:           {path}")


if __name__ == "__main__":
    parser = build_parser()
    args = parser.parse_args()
    main(args)